// This file has been autogenerated from a class added in the UI designer.

using System;
using CoreGraphics;
using Foundation;
using UIKit;

namespace Xamarin.AbbyyRtr.iOS.Sample
{
	public partial class RTRSelectedAreaView : UIView
	{
        public CGRect SelectedArea { get; set; }
            
//            : CGRect = CGRect.zero {
//        didSet {
//            DispatchQueue.main.async {
//                self.setNeedsDisplay()
//	}
//}
    // }


		public RTRSelectedAreaView (IntPtr handle) : base (handle)
		{
		}
	}
}
